### ISSUE TITLE
Failing to extract definitions form sentences with "known as" construction

### ISSUE THREAD

**Issue by alvaromorales** [infolab-csail/whoami#84]
It looks like we fail to get definitions from sentences with AKA clauses ("known as").

Example: "Arlotto Mainardi, known variously as Pievano Arlotto or Piovano Arlotto, was a priest known for jests and "pleasantries." List of subjects: `([u'Arlotto Mainardi', u'Pievano Arlotto', u'Piovano Arlotto', u'Piovano Arlotto'])`

Other examples:

```
MainThread - DEBUG -   .. whoami exception for: "Norma Sue Edwards Scott, known as Sue Scott, is a Republican member of the Arkansas House of Representatives from Rogers in Benton County in northwestern Arkansas." ([u'Sue Scott', u'Norma Sue Edwards Scott', u'Sue Scott (politician)'])

MainThread - DEBUG -   .. whoami exception for: "Indalecio León Zarasqueta Uriarte, known as Txikito de Eibar or Aizpiri txiki, was a Basque pelota player who participated in "pala", Hand-pelota, "remonte", long bat and short bat categories." ([u'Txikito de Eibar', u'Aizpiri txiki', u'Indalecio Le\xf3n Zarasqueta Uriarte', u'Indalecio Sarasqueta'])

MainThread - DEBUG -   .. whoami exception for: "Club Atlético Kimberley known as Kimberley de Mar del Plata is a sports club from Mar del Plata, Buenos Aires Province, Argentina." ([u'Club Atl\xe9tico Kimberley', u'Kimberley de Mar del Plata', u'Kimberley de Mar del Plata'])

MainThread - DEBUG -   .. whoami exception for: "Lawrence Fewell Roberts II, known as Robin Roberts and in his music career as "Rockin' Robin" Roberts, was an American singer best known for his performances in the early 1960s with The Wailers, a rock and roll band based in Tacoma, Washington." ([u'Robin Roberts', u'Lawrence Fewell Roberts II', u"Rockin' Robin Roberts"])

MainThread - DEBUG -   .. whoami exception for: "Rebuild of Evangelion, known in Japan as , is a Japanese animated film series and a reboot of the original "Neon Genesis Evangelion" anime TV series, produced by Studio Khara." ([u'Rebuild of Evangelion'])
```

**Comment by shu98** [comment]
Follow up to https://github.com/infolab-csail/whoami/issues/84#issue-140442474

**Norma Sue Edwards Scott:** This is a spaCy parsing issue. When we replace the subjects with "subject_number_00", spaCy fails to identify the correct root/nsubj. However, the newest version of spaCy seems to get it right. 

**Indalecio León Zarasqueta Uriarte:** same problem as before where replacing the subjects throws an error, but if we leave the subject variable as an empty list, spaCy parses fine. 

**Club Atlético Kimberley"** Bad grammar? I think the "known as" phrase should be offset with commas, which causes spaCy to parse the sentence incorrectly. Not sure if whoami should be able to handle this or if it should error and wait until Wikipedia updates.

**Lawrence Fewell Roberts II:** The newest version of spaCy parses this correctly. The current version that whoami does not, which is why we get an error. 

**Rebuild of Evangelion:** This no longer throws an error in whoami.

**Comment by hanryhu** [comment]
Probably after recent spaCy updates (https://github.com/infolab-csail/whoami/pull/133), all of the above examples now parse correctly with no errors, except for `Rebuild of Evangelion` which gives:
```
>>> get_assertion_definitions("Rebuild of Evangelion, known in Japan as , is a Japanese animated film series and a reboot of the original \"Neon Genesis Evangelion\" anime TV series, produced by Studio Khara.", subject=[u'Rebuild of Evangelion'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henryhu/whoami/whoami/query.py", line 44, in get_assertion_definitions
    entry = extract_assertion(assertion, subject=subject)
  File "/Users/henryhu/whoami/whoami/defextract.py", line 200, in extract_assertion
    postprocess_entry(entry, substitutions)
  File "/Users/henryhu/whoami/whoami/postprocess.py", line 268, in postprocess_entry
    filter_definitions(entry)
  File "/Users/henryhu/whoami/whoami/postprocess.py", line 219, in filter_definitions
    common_hypernym = get_common_hypernym(definition_nodes)
  File "/Users/henryhu/whoami/whoami/postprocess.py", line 248, in get_common_hypernym
    common_hypernym = nodes[i].common_hypernym(nodes[j])
  File "/Users/henryhu/whoami/whoami/deftree.py", line 136, in common_hypernym
    closest_ss_pair = max(filter(lambda ss_pair: ss_pair[0].wup_similarity(ss_pair[1]), ss_pairs), key=lambda ss_pair: ss_pair[0].wup_similarity(ss_pair[1]))
ValueError: max() arg is an empty sequence
```
This error doesn't appear to be related.
